---
- name: Install curl
  apt:
    name: curl
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Send curl request GET
  shell: >
    curl -L -H "Accept: application/vnd.github+json" \
         -H "Authorization: Bearer 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" \
         -H "X-GitHub-Api-Version: 2022-11-28" \
         "https://api.github.com/repos/therealminhduc/SLA_2024/actions/artifacts" | jq '.artifacts[1].archive_download_url' > idte.txt

- name: Send curl request SED
  shell: >
    sed 's/\"//g' idte.txt > frontid

- name: Send curl request DOWNLOAD
  shell: >
    curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer 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" -H "X-GitHub-Api-Version: 2022-11-28" -o firmaware.zip $(cat frontid)
  args:
    executable: /bin/bash

- name: Send curl request UNZIP1
  shell: >
    unzip -o firmaware.zip
  args:
    executable: /bin/bash

- name: Send curl request UNZIP
  shell: >
    unzip -o back_artifact.zip -d /var/www/
  args:
    executable: /bin/bash